server:
  port: 8080

app:
  name:
    xxx:
      yyy:
        zzz: zhudi

self:
    custom:
      config:
        sdkSecret: abc123
        host: https://www.zhudi.com
        port: ${server.port}

spring:
  datasource:                                 # 数据源相关的配置节点
    type: com.zaxxer.hikari.HikariDataSource  # 指定数据源的类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xd-springboot-forum?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: Star2035!
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 500KB # 文件上传大小的限制
      max-request-size: 2MB # 文件最大请求限制，用于批量

# Mybatis相关配置
mybatis:
  type-aliases-package: com.xindi.pojo        # 所有数据库表逆向后所一一映射的实体类 Entity/Bean
  mapper-locations: classpath:mappers/*.xml   # 所有mapper映射的文件所在目录位置

## 通用mapper配置
#mapper:
#  mappers: com.xindi.my.mapper.MyMapper       # 所有Mapper都需要实现的接口
#  not-empty: false              # 在进行数据库操作的时候，判断一个属性是否为空的时候，是否需要自动追加
#  identity: MYSQL
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页插件助手的配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true